insert into ist_Teilnehmer values ('C_001', 'KRS_00');
insert into ist_Teilnehmer values ('C_002', 'KRS_00');
insert into ist_Teilnehmer values ('C_004', 'KRS_00');
insert into ist_Teilnehmer values ('C_006', 'KRS_00');
insert into ist_Teilnehmer values ('C_007', 'KRS_00');
insert into ist_Teilnehmer values ('C_008', 'KRS_00');
insert into ist_Teilnehmer values ('C_009', 'KRS_00');
insert into ist_Teilnehmer values ('C_010', 'KRS_00');
insert into ist_Teilnehmer values ('C_012', 'KRS_00');
insert into ist_Teilnehmer values ('C_014', 'KRS_00');
insert into ist_Teilnehmer values ('C_015', 'KRS_00');
insert into ist_Teilnehmer values ('C_020', 'KRS_00');
insert into ist_Teilnehmer values ('C_024', 'KRS_00');
insert into ist_Teilnehmer values ('C_027', 'KRS_00');
insert into ist_Teilnehmer values ('C_001', 'KRS_00');
insert into ist_Teilnehmer values ('C_001', 'KRS_01');
insert into ist_Teilnehmer values ('C_002', 'KRS_01');
insert into ist_Teilnehmer values ('C_003', 'KRS_01');
insert into ist_Teilnehmer values ('C_006', 'KRS_01');
insert into ist_Teilnehmer values ('C_007', 'KRS_01');
insert into ist_Teilnehmer values ('C_011', 'KRS_01');
insert into ist_Teilnehmer values ('C_012', 'KRS_01');
insert into ist_Teilnehmer values ('C_013', 'KRS_01');
insert into ist_Teilnehmer values ('C_026', 'KRS_01');
insert into ist_Teilnehmer values ('C_027', 'KRS_01');
insert into ist_Teilnehmer values ('C_001','KRS_02');
insert into ist_Teilnehmer values ('C_002','KRS_02');
insert into ist_Teilnehmer values ('C_003','KRS_02');
insert into ist_Teilnehmer values ('C_009','KRS_02');
insert into ist_Teilnehmer values ('C_012','KRS_02');
insert into ist_Teilnehmer values ('C_016','KRS_02');
insert into ist_Teilnehmer values ('C_018','KRS_02');
insert into ist_Teilnehmer values ('C_019','KRS_02');
insert into ist_Teilnehmer values ('C_018','KRS_03');
insert into ist_Teilnehmer values ('C_019','KRS_03');
insert into ist_Teilnehmer values ('C_023','KRS_03');
insert into ist_Teilnehmer values ('C_026','KRS_03');
insert into ist_Teilnehmer values ('C_002','KRS_03');
insert into ist_Teilnehmer values ('C_005','KRS_03');
insert into ist_Teilnehmer values ('C_006', 'KRS_04');
insert into ist_Teilnehmer values ('C_007', 'KRS_04');
insert into ist_Teilnehmer values ('C_008', 'KRS_04');
insert into ist_Teilnehmer values ('C_009', 'KRS_04');
insert into ist_Teilnehmer values ('C_010', 'KRS_04');
insert into ist_Teilnehmer values ('C_011', 'KRS_04');
insert into ist_Teilnehmer values ('C_012', 'KRS_04');
insert into ist_Teilnehmer values ('C_013', 'KRS_04');
insert into ist_Teilnehmer values ('C_014', 'KRS_04');
insert into ist_Teilnehmer values ('C_015', 'KRS_04');
insert into ist_Teilnehmer values ('C_016', 'KRS_04');
insert into ist_Teilnehmer values ('C_017', 'KRS_04');
insert into ist_Teilnehmer values ('C_018', 'KRS_04');
insert into ist_Teilnehmer values ('C_019', 'KRS_04');
insert into ist_Teilnehmer values ('C_020', 'KRS_04');
insert into ist_Teilnehmer values ('C_021', 'KRS_04');
insert into ist_Teilnehmer values ('C_022', 'KRS_04');
insert into ist_Teilnehmer values ('C_023', 'KRS_04');
insert into ist_Teilnehmer values ('C_024', 'KRS_04');
insert into ist_Teilnehmer values ('C_025', 'KRS_04');
insert into ist_Teilnehmer values ('C_026', 'KRS_04');
insert into ist_Teilnehmer values ('C_027', 'KRS_04');
insert into ist_Teilnehmer values ('C_028', 'KRS_04');
insert into ist_Teilnehmer values ('C_002', 'KRS_04');
insert into ist_Teilnehmer values ('C_001', 'KRS_04');
insert into ist_Teilnehmer values ('C_004', 'KRS_05');
insert into ist_Teilnehmer values ('C_005', 'KRS_05');
insert into ist_Teilnehmer values ('C_006', 'KRS_05');
insert into ist_Teilnehmer values ('C_007', 'KRS_05');
insert into ist_Teilnehmer values ('C_008', 'KRS_05');
insert into ist_Teilnehmer values ('C_009', 'KRS_05');
insert into ist_Teilnehmer values ('C_010', 'KRS_05');
insert into ist_Teilnehmer values ('C_011', 'KRS_05');
insert into ist_Teilnehmer values ('C_012', 'KRS_05');
insert into ist_Teilnehmer values ('C_013', 'KRS_05');
insert into ist_Teilnehmer values ('C_014', 'KRS_05');
insert into ist_Teilnehmer values ('C_015', 'KRS_05');
insert into ist_Teilnehmer values ('C_016', 'KRS_05');
insert into ist_Teilnehmer values ('C_017', 'KRS_05');
insert into ist_Teilnehmer values ('C_018', 'KRS_05');
insert into ist_Teilnehmer values ('C_019', 'KRS_05');
insert into ist_Teilnehmer values ('C_020', 'KRS_05');
insert into ist_Teilnehmer values ('C_021', 'KRS_05');
insert into ist_Teilnehmer values ('C_022', 'KRS_05');
insert into ist_Teilnehmer values ('C_023', 'KRS_05');
insert into ist_Teilnehmer values ('C_001', 'KRS_06');
insert into ist_Teilnehmer values ('C_002', 'KRS_06');
insert into ist_Teilnehmer values ('C_003', 'KRS_06');
insert into ist_Teilnehmer values ('C_004', 'KRS_06');
insert into ist_Teilnehmer values ('C_005', 'KRS_06');
insert into ist_Teilnehmer values ('C_006', 'KRS_06');
insert into ist_Teilnehmer values ('C_007', 'KRS_06');
insert into ist_Teilnehmer values ('C_008', 'KRS_06');
insert into ist_Teilnehmer values ('C_009', 'KRS_06');
insert into ist_Teilnehmer values ('C_010', 'KRS_06');
insert into ist_Teilnehmer values ('C_011', 'KRS_06');
insert into ist_Teilnehmer values ('C_012', 'KRS_06');
insert into ist_Teilnehmer values ('C_013', 'KRS_06');
insert into ist_Teilnehmer values ('C_014', 'KRS_06');
insert into ist_Teilnehmer values ('C_015', 'KRS_06');
insert into ist_Teilnehmer values ('C_016', 'KRS_06');
insert into ist_Teilnehmer values ('C_017', 'KRS_06');
insert into ist_Teilnehmer values ('C_018', 'KRS_06');
insert into ist_Teilnehmer values ('C_019', 'KRS_06');
insert into ist_Teilnehmer values ('C_020', 'KRS_06');
insert into ist_Teilnehmer values ('C_021', 'KRS_06');
insert into ist_Teilnehmer values ('C_026', 'KRS_06');