INSERT INTO kategorien VALUES('KAT_00', 'CARDIO', 'Ausdauer');
INSERT INTO kategorien VALUES('KAT_01', 'KRAFT', 'Krafttraining');
INSERT INTO kategorien VALUES('KAT_02', 'KONTROLLE', 'Koerperkontrolle');
INSERT INTO kategorien VALUES('KAT_03', 'KRAFT', 'Bizeps');
INSERT INTO kategorien VALUES('KAT_04', 'KRAFT', 'Trizeps');
INSERT INTO kategorien VALUES('KAT_05', 'KRAFT', 'Unterarm');
INSERT INTO kategorien VALUES('KAT_06', 'KRAFT', 'Brust');
INSERT INTO kategorien VALUES('KAT_07', 'KRAFT', 'Obere Brust');
INSERT INTO kategorien VALUES('KAT_08', 'KRAFT', 'Bauch');
INSERT INTO kategorien VALUES('KAT_09', 'KRAFT', 'Quadrizeps');
INSERT INTO kategorien VALUES('KAT_10', 'KRAFT', 'Beinbeuger');
INSERT INTO kategorien VALUES('KAT_11', 'KRAFT', 'Abduktor');
INSERT INTO kategorien VALUES('KAT_12', 'KRAFT', 'Adduktor');
INSERT INTO kategorien VALUES('KAT_13', 'KRAFT', 'Gluteus');
INSERT INTO kategorien VALUES('KAT_14', 'KRAFT', 'Waden');
INSERT INTO kategorien VALUES('KAT_15', 'KRAFT', 'Latissimus');
INSERT INTO kategorien VALUES('KAT_16', 'KRAFT', 'Rhombus');
INSERT INTO kategorien VALUES('KAT_17', 'KRAFT', 'Nacken');
INSERT INTO kategorien VALUES('KAT_18', 'KRAFT', 'Unterer Rücken');
INSERT INTO kategorien VALUES('KAT_19', 'KRAFT', 'Schulter');
INSERT INTO kategorien VALUES('KAT_20', 'KRAFT', 'Vordere Schulter');
INSERT INTO kategorien VALUES('KAT_21', 'KRAFT', 'Hintere Schulter');