INSERT INTO KATEGORIEN VALUES('KAT_00', 'CARDIO', 'Ausdauer');
INSERT INTO KATEGORIEN VALUES('KAT_01', 'KRAFT', 'Krafttraining');
INSERT INTO KATEGORIEN VALUES('KAT_02', 'KONTROLLE', 'Koerperkontrolle');
