INSERT INTO TRAININGSEINHEITEN VALUES ('TE_00', 'Biking', 20, 'Indoor Biking',                                   'SG_017');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_01', 'Brustpresse', 15, 'Training an Maschine mit x Gewicht',         'SG_004');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_02', 'Schulterpresse', 15, 'Training an Maschine mit x Gewicht',      'SG_011');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_03', 'Beinbeuger', 15, 'Training an Maschine mit x Gewicht',          'SG_035');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_04', 'Beinstrecker', 20, 'Training an Maschine mit x Gewicht',        'SG_037');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_05', 'Rudern', 20, 'Training an Rudermaschine mit x Gewicht',         'SG_040');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_06', 'Abduktionsmaschine', 15, 'Training an Maschine mit x Gewicht',  'SG_041');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_07', 'Adduktionsmaschine', 15, 'Training an Maschine mit x Gewicht',  'SG_042');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_08', 'Crosstrainer', 30, 'Crosstrainer Workout',                      'SG_006');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_09', 'Rueckenstrecker', 15, 'Training an der Maschine mit x Gewicht', 'SG_023');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_10', 'Bauchpresse', 15, 'Training an der Maschine mit x Gewicht',     'SG_014');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_11', 'Beinpresse', 15, 'Training an der Maschine mit x Gewicht',      'SG_005');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_12', 'Schulterpresse', 15, 'Training an der Maschine mit x Gewicht',  'SG_011');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_13', 'Butterfly', 15, 'Training an der Maschine mit x Gewicht',       'SG_034');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_14', 'Bauchtraining', 15, 'Training mit der Fitnessmatte',            'SG_031');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_15', 'Laufband', 30, 'Laufband laufen',                               'SG_025');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_16', 'Laufband', 45, 'Laufband laufen',                               'SG_025');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_17', 'Bankdruecken', 15, 'An der Hantelbank mit x Gewicht',           'SG_009');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_18', 'Trizeps-Curls', 10, 'Kabelturm mit x Gewicht',                  'SG_015');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_19', 'Bizeps-Curls', 12, 'Hanteltraining mit x Gewicht',              'SG_012');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_20', 'Schulterdruecken', 15, 'Training an Schraegbank mit x Gewicht', 'SG_038');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_21', 'Bankdruecken', 15, 'An der Hantelbank mit x Gewicht',           'SG_009');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_22', 'Butterfly',15, 'Training an Maschine mit x Gewicht',            'SG_034');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_23', 'Schulterdruecken', 15, 'Training an Schraegbank mit x Gewicht', 'SG_038');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_24', 'Bizeps-Curls', 15, 'Hantelstange mit x Gewicht von Unten',      'SG_012');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_25', 'Trizeps-Curls',15, 'Kabelturm mit x Gewicht von Oben',          'SG_015');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_26', 'Beinpresse',15, 'Beinpresse mit x Gewicht',                     'SG_005');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_27', 'Rueckentraining',15, 'Latismuszug mit x Gewicht',               'SG_036');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_28', 'Bauchpresse',15, 'Bauchpresse mit x Gewicht',                   'SG_014');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_29', 'Rudern', 20, 'Training an Rudermaschine mit x Gewicht',         'SG_040');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_30', 'Sit-Ups', 12, 'Training an Maschine mit x Gewicht',             'SG_028');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_31', 'Biking', 30, 'Indoor Biking',                                   'SG_017');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_32', 'Stepper',20, 'Stepper',                                         'SG_001');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_33', 'Rudern',15, 'Rudermaschine',                                    'SG_040');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_34', 'Sit-Ups',15, 'Gymnastikball',                                   'SG_028');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_35', 'Biking',20, 'Indoor Biking',                                    'SG_017');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_36', 'Rueckentraining',15, 'Latismuszug',                             'SG_036');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_37', 'Abduktionsmaschine', 15, 'Training an Maschine mit x Gewicht',  'SG_041');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_38', 'Adduktionsmaschine', 15, 'Training an Maschine mit x Gewicht',  'SG_042');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_39', 'Laufband', 15, 'Laufband laufen',                               'SG_025');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_40', 'Stepper', 60, 'Aerobic Stepper',                                'SG_001');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_41', 'Crosstrainer', 60, 'Crosstrainer',                              'SG_006');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_42', 'Fitnessmatte', 60, 'Fitnessmatte',                              'SG_031');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_43', 'Faszienlockerung', 45, 'Faszienrolle',                          'SG_020');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_44', 'Biking', 90, 'Indoor Biking',                                   'SG_017');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_45', 'Gymnastik', 20, 'Gymnastikball',                                'SG_028');
INSERT INTO TRAININGSEINHEITEN VALUES ('TE_46', 'Hantelstange', 20, 'Freihanteln',                               'SG_012');