select k.NAME, t.TRAINER_ID
from KURSE k LEFT JOIN TRAINER t ON k.NAME
select  it.KUNDE_ID, t.TRAINER_ID, lk.TRAINER_ID, lk.KURS_ID,
from KURSE k, TRAINER t, IST_TEILNEHMER it LEFT JOIN LEITET_KURS lk ON lk.TRAINER_ID = t.TRAINER_ID
SELECT it.KUNDE_ID, COUNT(*) as c  FROM IST_TEILNEHMER it INNER JOIN LEITET_KURS lk ON lk.KURS_ID = it.KURS_ID
ORDER BY it.KUNDE_ID